### PR TITLE
Improved German translation

### PR DESCRIPTION
**Pull request by blobgo**
...and fixed some link to the German Wikipedia (e.g.: MITM, Salt)

# Notes
* BTW what should "Nothing illegal in DE on banner." mean? (on the English website this is BTW "Nothing illegal in NL on banner.")
* (line 336ff) Maybe even the examples of SNORM and so one are a bit outdated. At least we know another important (and big) one - Prism.

# Some sources
* https://dict.leo.org/ende/index_de.html#/search=Cryptography
* https://de.wikipedia.org/wiki/Open_Source (use the writing of "Open Source" from Wikipedia if it's used as a stand-alone word)
* https://de.wikipedia.org/wiki/Source_Code
* host provider --> colloquially "Hoster"
* awesome --> "großartig" sounds better "genial"; https://dict.leo.org/ende/?lang=de&search=awesome
* line 359: "Blööd" - Funny, this word doesn't exist in German at all: http://www.duden.de/suchen/dudenonline/Bo%C3%B6d; https://dict.leo.org/ende/index_de.html#/search=Bo%C3%B6d but it sounds like "[a German word for stupid] (https://dict.leo.org/ende/index_de.html#/search=bl%C3%B6d)"

### CODE REVIEW

**Comment by blobgo** [comment]
BTW how can I translate "Transparency"? It's not in the file...

**Comment by komachi** [comment]
Thanks! It should be NL because img.bi hosted in NL. SORM is Russian and ex-USSR surveillance system, it still works and was greatly improved recently. PRISM relay to service providers cooperation, so it's not a threat here, but I should add Tempora, Lawful Intercept and Monitoring and Golden Shield Project for sure. I tried to add examples from different countries because surveillance is not only US thing.

You can extract template with `grunt extract` and then use it in something like Poedit, it should contain all the recent strings.

**Comment by blobgo** [comment]
Okay, maybe I will do it later.

This are going to be many examples... :smile:
Maybe a generalized sentence instead of these examples would also fit, but this is your decision.

**Comment by komachi** [comment]
Added new strings to all *.po files and more mass surveillance projects examples in f722fda8f07b64e63afeef8b5abd2f40aa0c782e.

**Comment by blobgo** [comment]
Ahh thanks that's nice. :smiley:

**Pull request merged**
